name: Check a ci.erlang.mk project

on:
  workflow_call:

env:
  CI_ERLANG_MK: 1
  AUTO_CI_MASTER: weekly
  COWBOY_QUICER: ${{ vars.COWBOY_QUICER || 0 }}
  GUN_QUICER: ${{ vars.GUN_QUICER || 0 }}

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      erlang: ${{ steps.versions.outputs.erlang }}
      latest: ${{ steps.latest_version.outputs.latest }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout ci.erlang.mk repository
      uses: actions/checkout@v4
      with:
        repository: ninenines/ci.erlang.mk
        path: deps/ci.erlang.mk

    - name: Output Erlang/OTP versions
      id: versions
      run: |
        {
          echo "erlang<<EOF"
          make ci-list | jq -Rn '[inputs]'
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Output latest Erlang/OTP version
      id: latest_version
      run: |
        {
          echo "latest<<EOF"
          make ci-list | grep -v rc | grep -v master | tail -n1
          echo EOF
        } >> "$GITHUB_OUTPUT"

  dialyze:
    name: Dialyzer (${{ needs.prepare.outputs.latest }})
    needs: prepare
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '${{ needs.prepare.outputs.latest }}'
        version-type: strict

    - name: Checkout ci.erlang.mk repository
      uses: actions/checkout@v4
      with:
        repository: ninenines/ci.erlang.mk
        path: deps/ci.erlang.mk

    - name: Install Erlang problem matchers
      run: echo "::add-matcher::deps/ci.erlang.mk/.github/matchers/erlang-matchers.json"

    - name: Run Dialyzer
      run: make dialyze

  test-unix:
    name: Tests
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        erlang: ${{ fromJson(needs.prepare.outputs.erlang) }}
        os: [ubuntu-latest, macos-14]
        exclude:
          # MacOS support in setup-beam starts at OTP-25.
          - erlang: OTP-24.3.4.17
            os: macos-14
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '${{ matrix.erlang }}'
        version-type: strict

    - name: Checkout ci.erlang.mk repository
      uses: actions/checkout@v4
      with:
        repository: ninenines/ci.erlang.mk
        path: deps/ci.erlang.mk

    - name: Install Erlang problem matchers
      run: echo "::add-matcher::deps/ci.erlang.mk/.github/matchers/erlang-matchers.json"

    - name: Run tests (macOS)
      if: runner.os == 'macOS'
      run: >
        brew install coreutils make &&
        gmake -k ci-setup tests

    - name: Run tests (Unix)
      if: runner.os != 'macOS'
      run: make -k ci-setup tests

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Common Test logs (${{ matrix.erlang }} ${{ runner.os }})
        path: |
          logs/
#          !logs/**/log_private

  test-windows:
    name: Tests
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        erlang: ${{ fromJson(needs.prepare.outputs.erlang) }}
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      COWBOY_QUICER: 0
      GUN_QUICER: 0
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Erlang/OTP
      uses: essen/setup-beam@main
      with:
        otp-version: '${{ matrix.erlang }}'
        version-type: loose

    - name: Checkout ci.erlang.mk repository
      uses: actions/checkout@v4
      with:
        repository: ninenines/ci.erlang.mk
        path: deps/ci.erlang.mk

    - name: Install Erlang problem matchers
      run: echo "::add-matcher::deps/ci.erlang.mk/.github/matchers/erlang-matchers.json"

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          make

    - name: Run tests
      shell: msys2 {0}
      run: PATH=$INSTALL_DIR_FOR_OTP/bin:$PATH make -k ci-setup tests

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Common Test logs (${{ matrix.erlang }} ${{ runner.os }})
        path: |
          logs/
#          !logs/**/log_private
